---
:emowner:
  :username: emowner
  :balance: 98640
:emkeeper:
  :username: emkeeper
  :balance: 225200
:emuser:
  :username: emuser
  :balance: 50000
:apple:
  :username: apple
  :balance: 1200
:bmagent:
  :username: bmagent
  :balance: 1000
:bmproducer:
  :username: bmproducer
  :balance: 1000
:bmartist:
  :username: bmartist
  :balance: 1000
