---
:emowner:
  :username: emowner
  :balance: 100240
:emkeeper:
  :username: emkeeper
  :balance: 171800
:emuser:
  :username: emuser
  :balance: 50000
:apple:
  :username: apple
  :balance: 1200
:bmagent:
  :username: bmagent
  :balance: 200
:bmproducer:
  :username: bmproducer
  :balance: 200
:bmartist:
  :username: bmartist
  :balance: 200
