---
:emowner:
  :username: emowner
  :balance: 91940
:emkeeper:
  :username: emkeeper
  :balance: 648300
:emuser:
  :username: emuser
  :balance: 50000
:apple:
  :username: apple
  :balance: 1200
:bmagent:
  :username: bmagent
  :balance: 2500
:bmproducer:
  :username: bmproducer
  :balance: 2500
:bmartist:
  :username: bmartist
  :balance: 2500
