---
:emowner:
  :password: emowner pwd
  :scopes:
  - add_money
  - view_money
  - remove_money
:emkeeper:
  :password: emkeeper pwd
  :scopes:
  - add_money
  - view_money
:emuser:
  :password: emuser pwd
  :scopes:
  - view_money
