---
:emadmin:
  :username: emadmin
  :password: emadmin pwd
  :scopes:
  - add_money
  - view_money
  - remove_money
  - admin
:emowner:
  :username: emowner
  :password: emowner pwd
  :scopes:
  - add_money
  - view_money
  - remove_money
:emkeeper:
  :username: emkeeper
  :password: emkeeper pwd
  :scopes:
  - add_money
  - view_money
:emuser:
  :username: emuser
  :password: emuser pwd
  :scopes:
  - view_money
:bmagent:
  :username: bmagent
  :password: bmagent pwd
  :scopes:
  - view_money
  - add_money
:bmproducer:
  :username: bmproducer
  :password: bmproducer pwd
  :scopes:
  - view_money
  - add_money
:bmartist:
  :username: bmartist
  :password: bmartist pwd
  :scopes:
  - view_money
  - add_money
